### ISSUE TITLE
change resolution

### ISSUE THREAD

**Issue by SpookyTabz** [iProgramMC/NanoShellOS#8]
how can i change resolution to 1920x1080x32, i looked in video.c but still dosent work when i change it

**Comment by iProgramMC** [comment]
The bootloader allows for this.

In GRUB, add the following line to your menuentry:
```
menuentry "boot" {
	multiboot /boot/kernel.bin root=/ emergency=yes   // An example configuration
	module    /boot/initrd.tar
	set gfxpayload=1920x1080x32                       //<-- What you should add
	boot
}
```

In Limine, the following line needs to be added to limine.cfg:
```
RESOLUTION=1920x1080x32
```

If these don't work, one last thing to try is going into src/asm/multiboot.asm and change the prefered values (i.e. 1024 becomes 1920, and 768 becomes 1080)

**Comment by iProgramMC** [comment]
Please note that some computers may not support the native resolution of your monitor (one of my test machines oddly supports 1920x1440, but not 1920x1080). If none of these methods work, you can change your test machine, or type in the following commands in the grub command line:
- `set pager=1` disables scrolling unless you press some keys (so that the information doesn't scroll by and you can look carefully)
- `vbeinfo` lists all supported vbe modes (if 1920x1080x32 does not appear, I'm sorry to tell you that it's not supported).
